name: release-downloader

on:
    push:
        branches:
            - "master"
            - "backwards-compatibility"
    pull_request:
        branches:
            - "master"

jobs:
  check-directory:
    runs-on: ubuntu-latest
    steps:
        - uses: robinraju/release-downloader@v1.9
          with:
                repository: "awslabs/amazon-kinesis-client"
                latest: true
                zipBall: true
                out-file-path: "release-downloads"
                extract: true
        - run: ls release-downloads
        - run: rm -rf release-downloads




