name: release-downloader

on:
    push:
        branches:
            - "master"
            - "backwards-compatibility"
    pull_request:
        branches:
            - "master"

jobs:
  check-directory:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: gh release download -R awslabs/amazon-kinesis-client --archive=tar.gz --output tmp/kinesis-client.tar.gz
      - run: ls tmp
      - run: tar -xzf tmp/kinesis-client.tar.gz
      - run: ls
      - run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: cd amazon-kinesis-client-$RELEASE_VERSION
      - run: mvn -B package --file pom.xml -DskipITs
      - run: cd ..
      - run: mvn -B package --file pom.xml -DskipITs
      - run: ls /root/.m2/repository/
      - run: rm -rf tmp




