name: release-downloader

on:
    push:
        branches:
            - "master"
            - "backwards-compatibility"
    pull_request:
        branches:
            - "master"

jobs:
  check-directory:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: gh release download -R awslabs/amazon-kinesis-client --archive=tar.gz --output downloaded-files/kinesis-client.tar.gz
      - run: ls release-downloads
      - run: | 
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
      - run: rm -rf release-downloads
      - run: ls release-downloads




