name: release-downloader

on:
    push:
        branches:
            - "master"
            - "backwards-compatibility"
    pull_request:
        branches:
            - "master"

jobs:
  check-directory:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'corretto'
      - run: gh release download -R awslabs/amazon-kinesis-client --archive=tar.gz --output tmp/kinesis-client.tar.gz
      - run: ls tmp
      - run: tar -xzf tmp/kinesis-client.tar.gz
      - run: echo "RELEASE_VERSION=$(ls | grep amazon-kinesis-client | sed 's/.*-//')" >> $GITHUB_ENV
      - run: mvn -B package --file amazon-kinesis-client-$RELEASE_VERSION/pom.xml -DskipITs
      - run: mvn -B package --file pom.xml -DskipITs
      - run: ls /root/.m2/repository/
      - run: rm -rf tmp




